spring:
  application:
    name: "bella"

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      status:
        http-mapping:
          down: 500
          out_of_service: 503
          warning: 500
    shutdown:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

## Configuring info endpoint
info:
  app:
    name: bella
    description: This is the bella application
    version: 0.0.1

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.data.convert.CustomConversions: ERROR
    org.springframework.data.elasticsearch.support.VersionInfo: ERROR
    org.elasticsearch.client: TRACE
    org.apache.http: INFO
    org.ok.milki: INFO

springdoc:
  version: @springdoc.version@
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true