spring:
  application:
    name: "bella"

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.data.convert.CustomConversions: ERROR
    org.springframework.data.elasticsearch.support.VersionInfo: ERROR
    org.elasticsearch.client: TRACE
    org.apache.http: INFO
    org.ok.milki: INFO

springdoc:
  version: @springdoc.version@
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method